-- M4X STORE V2 - Supabase schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  icon text,
  description text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  slug text unique not null,
  description text,
  price bigint not null default 0 check (price >= 0),
  old_price bigint,
  cover_url text,
  gallery jsonb not null default '[]'::jsonb,
  delivery_type text not null default 'download' check (delivery_type in ('download','content','license','service','subscription','external')),
  stock_mode text not null default 'unlimited' check (stock_mode in ('unlimited','limited')),
  stock_limit integer check (stock_limit is null or stock_limit >= 0),
  sold_count integer not null default 0 check (sold_count >= 0),
  reserved_count integer not null default 0 check (reserved_count >= 0),
  file_path text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_code text unique not null,
  product_id uuid not null references public.products(id),
  quantity integer not null default 1 check (quantity > 0),
  amount bigint not null check (amount >= 0),
  customer_contact text,
  status text not null default 'pending' check (status in ('pending','paid','expired','cancelled','review')),
  access_token text not null,
  expires_at timestamptz not null,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references public.orders(id),
  transaction_id text unique not null,
  amount bigint not null,
  content text,
  account_number text,
  match_status text not null default 'received' check (match_status in ('received','matched','unmatched','review')),
  raw_data jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.license_keys (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  order_id uuid references public.orders(id),
  license_key text unique not null,
  status text not null default 'available' check (status in ('available','sold','disabled')),
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin');
$$;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.payments enable row level security;
alter table public.license_keys enable row level security;

-- Public storefront can only read active categories/products.
drop policy if exists "public read active categories" on public.categories;
create policy "public read active categories" on public.categories for select using (active=true or public.is_admin());
drop policy if exists "public read active products" on public.products;
create policy "public read active products" on public.products for select using (active=true or public.is_admin());

-- Admin CRUD.
drop policy if exists "admin categories all" on public.categories;
create policy "admin categories all" on public.categories for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin products all" on public.products;
create policy "admin products all" on public.products for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin orders all" on public.orders;
create policy "admin orders all" on public.orders for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin payments all" on public.payments;
create policy "admin payments all" on public.payments for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin license all" on public.license_keys;
create policy "admin license all" on public.license_keys for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "profile self read" on public.profiles;
create policy "profile self read" on public.profiles for select using (id=auth.uid() or public.is_admin());

-- Storage buckets.
insert into storage.buckets (id,name,public) values ('product-images','product-images',true) on conflict (id) do update set public=true;
insert into storage.buckets (id,name,public) values ('products-private','products-private',false) on conflict (id) do update set public=false;

drop policy if exists "admin upload product images" on storage.objects;
create policy "admin upload product images" on storage.objects for insert to authenticated with check (bucket_id='product-images' and public.is_admin());
drop policy if exists "admin manage product images" on storage.objects;
create policy "admin manage product images" on storage.objects for all to authenticated using (bucket_id='product-images' and public.is_admin()) with check (bucket_id='product-images' and public.is_admin());
drop policy if exists "admin manage private products" on storage.objects;
create policy "admin manage private products" on storage.objects for all to authenticated using (bucket_id='products-private' and public.is_admin()) with check (bucket_id='products-private' and public.is_admin());

-- Expire abandoned orders and release reservations.
create or replace function public.expire_pending_orders()
returns integer language plpgsql security definer set search_path=public as $$
declare r record; n integer:=0;
begin
  for r in select o.id,o.product_id,o.quantity from public.orders o where o.status='pending' and o.expires_at < now() for update skip locked loop
    update public.orders set status='expired' where id=r.id;
    update public.products set reserved_count=greatest(0,reserved_count-r.quantity),updated_at=now() where id=r.product_id and stock_mode='limited';
    n:=n+1;
  end loop;
  return n;
end $$;

-- Atomic order creation. Call only from Edge Function using service role.
create or replace function public.create_pending_order(p_product_id uuid,p_quantity integer default 1,p_contact text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare p public.products%rowtype; av integer; code text; token text; total bigint;
begin
  perform public.expire_pending_orders();
  if p_quantity is null or p_quantity < 1 or p_quantity > 20 then raise exception 'Số lượng không hợp lệ'; end if;
  select * into p from public.products where id=p_product_id and active=true for update;
  if not found then raise exception 'Sản phẩm không tồn tại hoặc đã ẩn'; end if;
  if p.stock_mode='limited' then
    av:=coalesce(p.stock_limit,0)-p.sold_count-p.reserved_count;
    if av < p_quantity then raise exception 'Sản phẩm đã hết hoặc không đủ số lượng'; end if;
  end if;
  total:=p.price*p_quantity;
  loop
    code:='M4X'||upper(substr(encode(gen_random_bytes(8),'hex'),1,10));
    exit when not exists(select 1 from public.orders where order_code=code);
  end loop;
  token:=encode(gen_random_bytes(32),'hex');
  insert into public.orders(order_code,product_id,quantity,amount,customer_contact,status,access_token,expires_at)
  values(code,p.id,p_quantity,total,p_contact,'pending',token,now()+interval '15 minutes');
  if p.stock_mode='limited' then update public.products set reserved_count=reserved_count+p_quantity,updated_at=now() where id=p.id; end if;
  return jsonb_build_object('order_code',code,'access_token',token,'amount',total,'expires_at',now()+interval '15 minutes','product_name',p.name,'delivery_type',p.delivery_type);
end $$;
revoke all on function public.create_pending_order(uuid,integer,text) from public,anon,authenticated;

-- Storefront can poll exact order only when both code + random access token match.
create or replace function public.get_order_status(p_order_code text,p_access_token text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare o record;
begin
  perform public.expire_pending_orders();
  select o.status,o.amount,o.expires_at,p.name as product_name,p.delivery_type into o
  from public.orders o join public.products p on p.id=o.product_id
  where o.order_code=p_order_code and o.access_token=p_access_token;
  if not found then return null; end if;
  return jsonb_build_object('status',o.status,'amount',o.amount,'expires_at',o.expires_at,'product_name',o.product_name,'delivery_type',o.delivery_type);
end $$;
grant execute on function public.get_order_status(text,text) to anon,authenticated;

-- Atomic SePay payment matching. Edge Function validates HMAC + bank account first.
create or replace function public.process_sepay_payment(p_transaction_id text,p_order_code text,p_amount bigint,p_content text,p_account text,p_raw jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare o public.orders%rowtype; p public.products%rowtype;
begin
  if exists(select 1 from public.payments where transaction_id=p_transaction_id) then return jsonb_build_object('result','duplicate'); end if;
  select * into o from public.orders where order_code=p_order_code for update;
  if not found then
    insert into public.payments(transaction_id,amount,content,account_number,match_status,raw_data) values(p_transaction_id,p_amount,p_content,p_account,'unmatched',p_raw);
    return jsonb_build_object('result','unmatched_order');
  end if;
  if o.status<>'pending' or o.expires_at < now() or o.amount<>p_amount then
    insert into public.payments(order_id,transaction_id,amount,content,account_number,match_status,raw_data) values(o.id,p_transaction_id,p_amount,p_content,p_account,'review',p_raw);
    if o.status='pending' then update public.orders set status='review' where id=o.id; end if;
    return jsonb_build_object('result','review');
  end if;
  insert into public.payments(order_id,transaction_id,amount,content,account_number,match_status,raw_data) values(o.id,p_transaction_id,p_amount,p_content,p_account,'matched',p_raw);
  update public.orders set status='paid',paid_at=now() where id=o.id;
  select * into p from public.products where id=o.product_id for update;
  if p.stock_mode='limited' then update public.products set reserved_count=greatest(0,reserved_count-o.quantity),sold_count=sold_count+o.quantity,updated_at=now() where id=p.id; else update public.products set sold_count=sold_count+o.quantity,updated_at=now() where id=p.id; end if;
  return jsonb_build_object('result','paid','order_id',o.id);
end $$;
revoke all on function public.process_sepay_payment(text,text,bigint,text,text,jsonb) from public,anon,authenticated;

-- Optional: if pg_cron is enabled in your project, run this after schema.sql:
-- select cron.schedule('m4x-expire-orders','* * * * *',$$select public.expire_pending_orders();$$);
