-- ============================================================
-- M4X STORE V4 COMPLETE
-- Chạy SAU schema V2 + M4X_STORE_V3_ACCOUNT_WALLET_FIXED.sql
-- ============================================================

begin;

create extension if not exists pgcrypto;

-- ============================================================
-- 0. ACCOUNT MODERATION
-- ============================================================
alter table public.profiles add column if not exists is_blocked boolean not null default false;
alter table public.profiles add column if not exists blocked_reason text;

-- ============================================================
-- 1. PRODUCT METADATA / VERSIONING
-- ============================================================
alter table public.products add column if not exists version_name text not null default '1.0';
alter table public.products add column if not exists changelog text;
alter table public.products add column if not exists compatibility text;
alter table public.products add column if not exists file_size_label text;
alter table public.products add column if not exists video_url text;
alter table public.products add column if not exists risk_note text;
alter table public.products add column if not exists sale_status text not null default 'active';

alter table public.products drop constraint if exists products_sale_status_check;
alter table public.products add constraint products_sale_status_check
check (sale_status in ('active','new','coming_soon','out_of_stock','discontinued'));

alter table public.orders add column if not exists purchased_version text;
alter table public.orders add column if not exists refunded_at timestamptz;
alter table public.orders add column if not exists refund_reason text;

alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check
check (status in ('pending','paid','expired','cancelled','review','refunded'));

create table if not exists public.product_updates (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  version_name text not null,
  changelog text,
  created_at timestamptz not null default now(),
  unique(product_id, version_name)
);

-- ============================================================
-- 2. NOTIFICATIONS
-- ============================================================
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade,
  title text not null,
  body text,
  type text not null default 'info'
    check (type in ('info','topup','purchase','refund','update','system')),
  reference text,
  created_at timestamptz not null default now()
);

create table if not exists public.notification_reads (
  notification_id uuid not null references public.notifications(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key(notification_id, user_id)
);

create index if not exists idx_notifications_user_created
on public.notifications(user_id, created_at desc);

-- ============================================================
-- 3. SECURITY / DOWNLOAD LOGS / RATE LIMIT
-- ============================================================
create table if not exists public.rate_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  action text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_rate_events_user_action_created
on public.rate_events(user_id, action, created_at desc);

create table if not exists public.download_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  order_id uuid references public.orders(id) on delete set null,
  product_id uuid references public.products(id) on delete set null,
  ip text,
  user_agent text,
  created_at timestamptz not null default now()
);

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  detail text,
  ip text,
  created_at timestamptz not null default now()
);

-- ============================================================
-- 4. RLS
-- ============================================================
alter table public.product_updates enable row level security;
alter table public.notifications enable row level security;
alter table public.notification_reads enable row level security;
alter table public.rate_events enable row level security;
alter table public.download_logs enable row level security;
alter table public.security_events enable row level security;

drop policy if exists "product updates admin all" on public.product_updates;
create policy "product updates admin all"
on public.product_updates for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "product updates public read" on public.product_updates;
create policy "product updates public read"
on public.product_updates for select
using (
  exists (
    select 1 from public.products p
    where p.id=product_id and (p.active=true or public.is_admin())
  )
);

drop policy if exists "notifications own read" on public.notifications;
create policy "notifications own read"
on public.notifications for select to authenticated
using (user_id is null or user_id=auth.uid() or public.is_admin());

drop policy if exists "notifications admin all" on public.notifications;
create policy "notifications admin all"
on public.notifications for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "notification reads own" on public.notification_reads;
create policy "notification reads own"
on public.notification_reads for select to authenticated
using (user_id=auth.uid() or public.is_admin());

drop policy if exists "downloads admin read" on public.download_logs;
create policy "downloads admin read"
on public.download_logs for select to authenticated
using (public.is_admin());

drop policy if exists "security admin read" on public.security_events;
create policy "security admin read"
on public.security_events for select to authenticated
using (public.is_admin());

grant select on public.product_updates to anon,authenticated;
grant select on public.notifications to authenticated;
grant select on public.notification_reads to authenticated;
grant select on public.download_logs to authenticated;
grant select on public.security_events to authenticated;

-- ============================================================
-- 5. INTERNAL RATE LIMIT
-- ============================================================
create or replace function public.m4x_enforce_rate_limit(
  p_action text,
  p_max_hits integer,
  p_window_seconds integer
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  uid uuid := auth.uid();
  hits integer;
begin
  if uid is null then raise exception 'Bạn chưa đăng nhập'; end if;

  delete from public.rate_events
  where created_at < now() - interval '1 day';

  select count(*) into hits
  from public.rate_events
  where user_id=uid
    and action=p_action
    and created_at > now() - make_interval(secs => p_window_seconds);

  if hits >= p_max_hits then
    raise exception 'Thao tác quá nhanh. Vui lòng thử lại sau.';
  end if;

  insert into public.rate_events(user_id,action) values(uid,p_action);
end;
$$;

revoke all on function public.m4x_enforce_rate_limit(text,integer,integer)
from public,anon,authenticated;

-- ============================================================
-- 6. PROFILE
-- ============================================================
create or replace function public.update_profile_name(p_display_name text)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare
  uid uuid := auth.uid();
  v text := trim(coalesce(p_display_name,''));
begin
  if uid is null then raise exception 'Bạn chưa đăng nhập'; end if;
  if char_length(v) < 2 or char_length(v) > 40 then
    raise exception 'Tên hiển thị phải từ 2 đến 40 ký tự';
  end if;

  update public.profiles set display_name=v where id=uid;
  return v;
end;
$$;

revoke all on function public.update_profile_name(text) from public,anon;
grant execute on function public.update_profile_name(text) to authenticated;

-- ============================================================
-- 7. NOTIFICATION READ
-- ============================================================
create or replace function public.mark_notification_read(p_notification_id uuid)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'Bạn chưa đăng nhập'; end if;
  if not exists (
    select 1 from public.notifications
    where id=p_notification_id
      and (user_id is null or user_id=uid)
  ) then raise exception 'Thông báo không tồn tại'; end if;

  insert into public.notification_reads(notification_id,user_id)
  values(p_notification_id,uid)
  on conflict(notification_id,user_id) do nothing;
end;
$$;

create or replace function public.mark_all_notifications_read()
returns void
language plpgsql
security definer
set search_path=public
as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'Bạn chưa đăng nhập'; end if;

  insert into public.notification_reads(notification_id,user_id)
  select n.id,uid
  from public.notifications n
  where n.user_id is null or n.user_id=uid
  on conflict(notification_id,user_id) do nothing;
end;
$$;

revoke all on function public.mark_notification_read(uuid) from public,anon;
revoke all on function public.mark_all_notifications_read() from public,anon;
grant execute on function public.mark_notification_read(uuid) to authenticated;
grant execute on function public.mark_all_notifications_read() to authenticated;

-- ============================================================
-- 8. CREATE TOPUP - RATE LIMITED
-- ============================================================
create or replace function public.create_wallet_topup(p_amount bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  uid uuid := auth.uid();
  code text;
  exp timestamptz := now() + interval '15 minutes';
begin
  if uid is null then raise exception 'Bạn chưa đăng nhập'; end if;
  if exists(select 1 from public.profiles where id=uid and is_blocked=true) then
    raise exception 'Tài khoản đang bị khóa. Liên hệ Admin.';
  end if;
  perform public.m4x_enforce_rate_limit('create_topup',5,60);

  if p_amount is null or p_amount < 10000 or p_amount > 5000000 then
    raise exception 'Số tiền nạp từ 10.000đ đến 5.000.000đ';
  end if;

  update public.topups set status='expired'
  where user_id=uid and status='pending' and expires_at<now();

  loop
    code := 'NAP' || upper(substr(md5(
      random()::text || clock_timestamp()::text || uid::text
    ),1,10));
    exit when not exists(select 1 from public.topups where topup_code=code);
  end loop;

  insert into public.topups(user_id,topup_code,amount,status,expires_at)
  values(uid,code,p_amount,'pending',exp);

  return jsonb_build_object(
    'topup_code',code,'amount',p_amount,'expires_at',exp
  );
end;
$$;

revoke all on function public.create_wallet_topup(bigint) from public,anon;
grant execute on function public.create_wallet_topup(bigint) to authenticated;

-- ============================================================
-- 9. BUY ONCE / STORE CREDIT
-- ============================================================
create or replace function public.wallet_purchase(
  p_product_id uuid,
  p_quantity integer default 1
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  uid uuid := auth.uid();
  prof public.profiles%rowtype;
  prod public.products%rowtype;
  total bigint;
  av integer;
  code text;
  token text;
  new_balance bigint;
begin
  if uid is null then raise exception 'Bạn chưa đăng nhập'; end if;
  perform public.m4x_enforce_rate_limit('wallet_purchase',8,60);

  if p_quantity is null or p_quantity<>1 then
    raise exception 'Mỗi tài khoản chỉ mua một lần cho mỗi sản phẩm';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(uid::text || ':' || p_product_id::text,0)
  );

  if exists (
    select 1 from public.orders
    where user_id=uid and product_id=p_product_id and status='paid'
  ) then
    raise exception 'Bạn đã mua sản phẩm này';
  end if;

  select * into prof from public.profiles where id=uid for update;
  if not found then raise exception 'Không tìm thấy tài khoản'; end if;
  if prof.is_blocked then
    raise exception 'Tài khoản đang bị khóa. Liên hệ Admin.';
  end if;

  select * into prod
  from public.products
  where id=p_product_id and active=true
  for update;

  if not found then raise exception 'Sản phẩm không tồn tại hoặc đã ẩn'; end if;

  if prod.sale_status='coming_soon' then raise exception 'Sản phẩm sắp ra mắt'; end if;
  if prod.sale_status='discontinued' then raise exception 'Sản phẩm đã ngừng bán'; end if;
  if prod.sale_status='out_of_stock' then raise exception 'Sản phẩm đã hết hàng'; end if;

  if prod.stock_mode='limited' then
    av:=coalesce(prod.stock_limit,0)-prod.sold_count-prod.reserved_count;
    if av<1 then raise exception 'Sản phẩm đã hết hàng'; end if;
  end if;

  total:=prod.price;
  if prof.balance<total then
    raise exception 'Số dư không đủ. Bạn cần nạp thêm %đ', total-prof.balance;
  end if;

  loop
    code:='M4XW'||upper(substr(md5(
      random()::text || clock_timestamp()::text || uid::text
    ),1,10));
    exit when not exists(select 1 from public.orders where order_code=code);
  end loop;

  token:=md5(random()::text||clock_timestamp()::text||uid::text)
       ||md5(random()::text||code);

  update public.profiles
  set balance=balance-total
  where id=uid
  returning balance into new_balance;

  update public.products
  set sold_count=sold_count+1,updated_at=now()
  where id=prod.id;

  insert into public.orders(
    order_code,product_id,quantity,amount,customer_contact,status,
    access_token,expires_at,paid_at,user_id,payment_method,purchased_version
  )
  values(
    code,prod.id,1,total,null,'paid',token,
    now()+interval '10 years',now(),uid,'wallet',prod.version_name
  );

  insert into public.wallet_transactions(
    user_id,amount,type,description,reference
  )
  values(uid,-total,'purchase','Mua '||prod.name,code);

  insert into public.notifications(
    user_id,title,body,type,reference
  )
  values(
    uid,'Mua hàng thành công',
    'Bạn đã sở hữu '||prod.name||'. Có thể tải lại bất cứ lúc nào.',
    'purchase',code
  );

  return jsonb_build_object(
    'order_code',code,
    'access_token',token,
    'amount',total,
    'product_name',prod.name,
    'delivery_type',prod.delivery_type,
    'balance_after',new_balance,
    'version_name',prod.version_name
  );
end;
$$;

revoke all on function public.wallet_purchase(uuid,integer) from public,anon;
grant execute on function public.wallet_purchase(uuid,integer) to authenticated;

-- ============================================================
-- 10. SEPAY WALLET TOPUP
-- ============================================================
create or replace function public.process_wallet_topup(
  p_transaction_id text,
  p_topup_code text,
  p_amount bigint,
  p_content text,
  p_account text,
  p_raw jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare t public.topups%rowtype;
begin
  if p_transaction_id is null or trim(p_transaction_id)='' then
    raise exception 'Thiếu transaction id';
  end if;

  if exists (
    select 1 from public.topups where bank_transaction_id=p_transaction_id
  ) then
    return jsonb_build_object('result','duplicate');
  end if;

  select * into t from public.topups
  where topup_code=upper(trim(p_topup_code))
  for update;

  if not found then return jsonb_build_object('result','unmatched_topup'); end if;
  if t.status='paid' then return jsonb_build_object('result','already_paid'); end if;

  if t.status<>'pending' or t.expires_at<now() or t.amount<>p_amount then
    update public.topups
    set status='review',bank_transaction_id=p_transaction_id
    where id=t.id;
    return jsonb_build_object('result','review');
  end if;

  update public.profiles set balance=balance+p_amount where id=t.user_id;

  insert into public.wallet_transactions(
    user_id,amount,type,description,reference
  )
  values(t.user_id,p_amount,'topup','Nạp tiền qua ngân hàng',t.topup_code);

  update public.topups
  set status='paid',paid_at=now(),bank_transaction_id=p_transaction_id
  where id=t.id;

  insert into public.notifications(user_id,title,body,type,reference)
  values(
    t.user_id,'Nạp tiền thành công',
    'Đã cộng '||to_char(p_amount,'FM999G999G999')||'đ vào số dư M4X STORE.',
    'topup',t.topup_code
  );

  return jsonb_build_object(
    'result','paid','user_id',t.user_id,'amount',p_amount
  );
end;
$$;

revoke all on function public.process_wallet_topup(
  text,text,bigint,text,text,jsonb
) from public,anon,authenticated;

-- ============================================================
-- 11. ADMIN REFUND TO STORE CREDIT
-- ============================================================
create or replace function public.admin_refund_order(
  p_order_id uuid,
  p_reason text default 'Hoàn tiền bởi Admin'
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  o public.orders%rowtype;
  new_balance bigint;
begin
  if not public.is_admin() then raise exception 'Không có quyền Admin'; end if;

  select * into o from public.orders where id=p_order_id for update;
  if not found then raise exception 'Không tìm thấy đơn hàng'; end if;
  if o.status='refunded' then raise exception 'Đơn này đã được hoàn tiền'; end if;
  if o.status<>'paid' then raise exception 'Chỉ hoàn tiền cho đơn đã thanh toán'; end if;
  if o.user_id is null then
    raise exception 'Đơn không gắn với tài khoản, không thể hoàn vào số dư';
  end if;

  update public.profiles
  set balance=balance+o.amount
  where id=o.user_id
  returning balance into new_balance;

  insert into public.wallet_transactions(
    user_id,amount,type,description,reference
  )
  values(
    o.user_id,o.amount,'refund',
    coalesce(nullif(trim(p_reason),''),'Hoàn tiền bởi Admin'),
    o.order_code
  );

  update public.orders
  set status='refunded',refunded_at=now(),refund_reason=p_reason
  where id=o.id;

  update public.products
  set sold_count=greatest(0,sold_count-o.quantity),updated_at=now()
  where id=o.product_id;

  insert into public.notifications(user_id,title,body,type,reference)
  values(
    o.user_id,'Đã hoàn tiền',
    'Đơn '||o.order_code||' đã được hoàn '||
    to_char(o.amount,'FM999G999G999')||'đ vào số dư.',
    'refund',o.order_code
  );

  return jsonb_build_object(
    'order_code',o.order_code,
    'refund_amount',o.amount,
    'balance_after',new_balance
  );
end;
$$;

revoke all on function public.admin_refund_order(uuid,text) from public,anon;
grant execute on function public.admin_refund_order(uuid,text) to authenticated;


-- ============================================================
-- 11B. ADMIN BLOCK / UNBLOCK ACCOUNT
-- ============================================================
create or replace function public.admin_set_user_blocked(
  p_user_id uuid,
  p_blocked boolean,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.is_admin() then raise exception 'Không có quyền Admin'; end if;
  if p_user_id=auth.uid() and p_blocked then
    raise exception 'Không thể tự khóa tài khoản Admin đang đăng nhập';
  end if;

  update public.profiles
  set is_blocked=p_blocked,
      blocked_reason=case when p_blocked then nullif(trim(coalesce(p_reason,'')),'') else null end
  where id=p_user_id;

  insert into public.notifications(user_id,title,body,type,reference)
  values(
    p_user_id,
    case when p_blocked then 'Tài khoản bị tạm khóa' else 'Tài khoản đã được mở khóa' end,
    case when p_blocked
      then coalesce(nullif(trim(coalesce(p_reason,'')),''),'Liên hệ Admin để biết thêm chi tiết.')
      else 'Bạn có thể tiếp tục sử dụng M4X STORE.'
    end,
    'system','ACCOUNT'
  );
end;
$$;

revoke all on function public.admin_set_user_blocked(uuid,boolean,text) from public,anon;
grant execute on function public.admin_set_user_blocked(uuid,boolean,text) to authenticated;

-- ============================================================
-- 12. ADMIN PUBLISH PRODUCT UPDATE + NOTIFY OWNERS
-- ============================================================
create or replace function public.admin_publish_product_update(
  p_product_id uuid,
  p_version_name text,
  p_changelog text
)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.is_admin() then raise exception 'Không có quyền Admin'; end if;

  update public.products
  set version_name=trim(p_version_name),
      changelog=p_changelog,
      updated_at=now()
  where id=p_product_id;

  insert into public.product_updates(product_id,version_name,changelog)
  values(p_product_id,trim(p_version_name),p_changelog)
  on conflict(product_id,version_name)
  do update set changelog=excluded.changelog,created_at=now();

  insert into public.notifications(user_id,title,body,type,reference)
  select distinct
    o.user_id,
    'Sản phẩm có bản cập nhật',
    p.name||' đã cập nhật lên phiên bản '||trim(p_version_name)||
      coalesce(E'\n'||nullif(trim(p_changelog),''),''),
    'update',
    p_product_id::text
  from public.orders o
  join public.products p on p.id=o.product_id
  where o.product_id=p_product_id
    and o.status='paid'
    and o.user_id is not null;
end;
$$;

revoke all on function public.admin_publish_product_update(uuid,text,text)
from public,anon;
grant execute on function public.admin_publish_product_update(uuid,text,text)
to authenticated;

notify pgrst, 'reload schema';
commit;
