-- ============================================================
-- M4X STORE V19 — TELEGRAM MINI APP + ONLINE UPDATE
-- Chạy SAU M4X_HERO_MANAGER_V18_3.sql
-- Không xóa dữ liệu cũ.
-- ============================================================
begin;

create extension if not exists pgcrypto;

create table if not exists public.telegram_users (
  telegram_user_id bigint primary key,
  username text,
  first_name text,
  last_name text,
  language_code text,
  photo_url text,
  allows_write_to_pm boolean not null default false,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.telegram_admins (
  telegram_user_id bigint primary key,
  active boolean not null default true,
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.telegram_admin_audit (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint not null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.store_app_release (
  id text primary key default 'main',
  version text not null default '19.0.0',
  build integer not null default 1900 check (build > 0),
  message text not null default 'M4X Store đã có bản cập nhật mới.',
  mandatory boolean not null default false,
  auto_reload boolean not null default false,
  force_reload_token text not null default gen_random_uuid()::text,
  updated_at timestamptz not null default now()
);

insert into public.store_app_release(id,version,build,message,mandatory,auto_reload)
values('main','19.0.0',1900,'M4X Store Telegram Mini App V19 đã sẵn sàng.',false,false)
on conflict(id) do nothing;

alter table public.telegram_users enable row level security;
alter table public.telegram_admins enable row level security;
alter table public.telegram_admin_audit enable row level security;
alter table public.store_app_release enable row level security;

-- Telegram user/admin chỉ được đọc/ghi qua Edge Function dùng secret key.
revoke all on public.telegram_users from anon,authenticated;
revoke all on public.telegram_admins from anon,authenticated;
revoke all on public.telegram_admin_audit from anon,authenticated;

-- Release là thông tin công khai để web kiểm tra update.
drop policy if exists "m4x release public read" on public.store_app_release;
create policy "m4x release public read" on public.store_app_release
for select to anon,authenticated using(true);
grant select on public.store_app_release to anon,authenticated;

create index if not exists idx_tg_users_last_seen on public.telegram_users(last_seen_at desc);
create index if not exists idx_tg_audit_created on public.telegram_admin_audit(created_at desc);

notify pgrst,'reload schema';
commit;
