-- ============================================================
-- M4X STORE V19.1 — TELEGRAM CHANNEL AUTO POST
-- Chạy SAU V18.3 Hero Manager + V19 Telegram Mini App.
-- Project hiện tại: cpkyzqmpqxcydsavobcf.supabase.co
-- Không xóa dữ liệu cũ.
-- ============================================================

create extension if not exists pgcrypto;
create extension if not exists pg_cron;
create extension if not exists pg_net;

-- 1) Cấu hình tự động đăng Channel
create table if not exists public.telegram_channel_settings (
  id text primary key default 'main',
  enabled boolean not null default true,
  timezone text not null default 'Asia/Ho_Chi_Minh',
  daily_enabled boolean not null default true,
  daily_time_1 time not null default '08:00',
  daily_time_2 time not null default '20:00',
  new_product_enabled boolean not null default true,
  hero_enabled boolean not null default true,
  online_update_enabled boolean not null default true,
  repost_enabled boolean not null default false,
  repost_days integer not null default 3 check (repost_days between 1 and 30),
  worker_secret_hash text,
  updated_at timestamptz not null default now()
);

insert into public.telegram_channel_settings(id)
values('main')
on conflict(id) do nothing;

-- 2) Hàng đợi và log bài đã đăng
create table if not exists public.telegram_channel_queue (
  id bigint generated by default as identity primary key,
  event_type text not null check(event_type in ('daily_store','repost_store','new_product','hero','online_update','manual_store')),
  dedupe_key text not null unique,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check(status in ('pending','sent','failed','skipped')),
  available_at timestamptz not null default now(),
  attempts integer not null default 0,
  last_error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_tg_channel_queue_pending
  on public.telegram_channel_queue(status, available_at, created_at);

create table if not exists public.telegram_channel_posts (
  id bigint generated by default as identity primary key,
  event_type text not null,
  dedupe_key text not null unique,
  telegram_message_id bigint,
  payload jsonb not null default '{}'::jsonb,
  posted_at timestamptz not null default now()
);

create index if not exists idx_tg_channel_posts_time
  on public.telegram_channel_posts(posted_at desc);

alter table public.telegram_channel_settings enable row level security;
alter table public.telegram_channel_queue enable row level security;
alter table public.telegram_channel_posts enable row level security;
revoke all on public.telegram_channel_settings from anon,authenticated;
revoke all on public.telegram_channel_queue from anon,authenticated;
revoke all on public.telegram_channel_posts from anon,authenticated;

-- 3) Helper enqueue idempotent
create or replace function public.m4x_enqueue_channel_event(
  p_event_type text,
  p_dedupe_key text,
  p_payload jsonb default '{}'::jsonb,
  p_available_at timestamptz default now()
) returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare v_id bigint;
begin
  insert into public.telegram_channel_queue(event_type,dedupe_key,payload,available_at)
  values(p_event_type,p_dedupe_key,coalesce(p_payload,'{}'::jsonb),coalesce(p_available_at,now()))
  on conflict(dedupe_key) do nothing
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.m4x_enqueue_channel_event(text,text,jsonb,timestamptz) from public,anon,authenticated;

-- 4) Sản phẩm mới: INSERT active hoặc lần đầu chuyển active=true
create or replace function public.m4x_tg_product_publish_trigger()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if (tg_op='INSERT' and new.active is true)
     or (tg_op='UPDATE' and new.active is true and coalesce(old.active,false) is false) then
    perform public.m4x_enqueue_channel_event(
      'new_product',
      'product:'||new.id::text||':published',
      jsonb_build_object(
        'id',new.id,
        'name',new.name,
        'description',new.description,
        'price',new.price,
        'old_price',new.old_price,
        'cover_url',new.cover_url,
        'created_at',new.created_at
      )
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_m4x_tg_product_publish on public.products;
create trigger trg_m4x_tg_product_publish
after insert or update of active on public.products
for each row execute function public.m4x_tg_product_publish_trigger();

-- 5) Hero/Flash Sale mới
create or replace function public.m4x_tg_hero_trigger()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if new.id='main' and new.enabled is true then
    if tg_op='INSERT' then
      perform public.m4x_enqueue_channel_event(
        'hero',
        'hero:'||to_char(coalesce(new.updated_at,now()),'YYYYMMDDHH24MISSMS'),
        to_jsonb(new)
      );
    elsif
      old.enabled is distinct from new.enabled or
      old.variant is distinct from new.variant or
      old.eyebrow is distinct from new.eyebrow or
      old.title is distinct from new.title or
      old.accent_text is distinct from new.accent_text or
      old.description is distinct from new.description or
      old.image_url is distinct from new.image_url or
      old.starts_at is distinct from new.starts_at or
      old.ends_at is distinct from new.ends_at
    then
      perform public.m4x_enqueue_channel_event(
      'hero',
      'hero:'||to_char(coalesce(new.updated_at,now()),'YYYYMMDDHH24MISSMS'),
        to_jsonb(new)
      );
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_m4x_tg_hero on public.store_hero_settings;
create trigger trg_m4x_tg_hero
after insert or update on public.store_hero_settings
for each row execute function public.m4x_tg_hero_trigger();

-- 6) Online Update: chỉ đăng khi Admin thực sự "Phát cập nhật" (token đổi)
create or replace function public.m4x_tg_release_trigger()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if new.id='main' and old.force_reload_token is distinct from new.force_reload_token then
    perform public.m4x_enqueue_channel_event(
      'online_update',
      'release:'||new.force_reload_token,
      to_jsonb(new)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_m4x_tg_release on public.store_app_release;
create trigger trg_m4x_tg_release
after update on public.store_app_release
for each row execute function public.m4x_tg_release_trigger();

-- 7) Secret cho worker được sinh tự động, lưu mã hóa trong Vault.
-- Edge Function chỉ lưu hash, nên người dùng không phải copy/paste secret.
do $$
declare
  v_secret text;
begin
  select decrypted_secret into v_secret
  from vault.decrypted_secrets
  where name='m4x_channel_worker_secret_v191'
  order by updated_at desc
  limit 1;

  if v_secret is null then
    v_secret := encode(gen_random_bytes(24),'hex');
    perform vault.create_secret(v_secret,'m4x_channel_worker_secret_v191','M4X Telegram Channel Worker V19.1');
  end if;

  update public.telegram_channel_settings
  set worker_secret_hash=encode(digest(v_secret,'sha256'),'hex'),updated_at=now()
  where id='main';
end $$;

-- Project URL riêng của project M4X Store hiện tại.
do $$
begin
  if not exists(select 1 from vault.decrypted_secrets where name='m4x_channel_project_url_v191') then
    perform vault.create_secret(
      'https://cpkyzqmpqxcydsavobcf.supabase.co',
      'm4x_channel_project_url_v191',
      'M4X project URL for Telegram Channel Worker V19.1'
    );
  end if;
end $$;

-- 8) Cron gọi worker mỗi phút. Worker tự quyết định 08:00 / 20:00,
--    xử lý queue sản phẩm/Hero/update và repost X ngày.
do $$
declare r record;
begin
  for r in select jobid from cron.job where jobname='m4x-channel-worker-v19-1' loop
    perform cron.unschedule(r.jobid);
  end loop;
end $$;

select cron.schedule(
  'm4x-channel-worker-v19-1',
  '* * * * *',
  $$
  select net.http_post(
    url := (
      select decrypted_secret from vault.decrypted_secrets
      where name='m4x_channel_project_url_v191'
      order by updated_at desc limit 1
    ) || '/functions/v1/telegram-channel-worker',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'x-m4x-worker-secret',(
        select decrypted_secret from vault.decrypted_secrets
        where name='m4x_channel_worker_secret_v191'
        order by updated_at desc limit 1
      )
    ),
    body := jsonb_build_object('source','cron','time',now()),
    timeout_milliseconds := 10000
  ) as request_id;
  $$
);

notify pgrst,'reload schema';
