-- ============================================================
-- M4X STORE V19.4 — AI CAPTION + TELEGRAM BUTTON ADMIN
-- Chạy SAU V19.3.
-- Không xóa dữ liệu cũ.
-- ============================================================

begin;

create extension if not exists pgcrypto;

-- 1) Emergency purchase gate controlled by Telegram Admin.
create table if not exists public.m4x_store_control (
  id text primary key default 'main' check (id='main'),
  purchases_enabled boolean not null default true,
  purchase_lock_reason text not null default 'M4X STORE đang tạm khóa mua hàng. Vui lòng quay lại sau.',
  updated_by text,
  updated_at timestamptz not null default now()
);

insert into public.m4x_store_control(id)
values('main')
on conflict(id) do nothing;

alter table public.m4x_store_control enable row level security;
revoke all on public.m4x_store_control from public,anon,authenticated;

create or replace function public.m4x_purchase_gate_trigger()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_enabled boolean := true;
  v_reason text := 'M4X STORE đang tạm khóa mua hàng. Vui lòng quay lại sau.';
begin
  select purchases_enabled, purchase_lock_reason
    into v_enabled, v_reason
  from public.m4x_store_control
  where id='main';

  if coalesce(v_enabled,true) = false then
    raise exception '%', coalesce(nullif(trim(v_reason),''),'M4X STORE đang tạm khóa mua hàng. Vui lòng quay lại sau.');
  end if;

  return new;
end;
$$;

-- Chặn mọi đường tạo đơn mới (wallet/cart/bank/Edge Function) khi Admin khóa mua hàng.
drop trigger if exists trg_m4x_purchase_gate on public.orders;
create trigger trg_m4x_purchase_gate
before insert on public.orders
for each row execute function public.m4x_purchase_gate_trigger();

create or replace function public.m4x_store_purchase_status()
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
  select jsonb_build_object(
    'purchases_enabled', coalesce(purchases_enabled,true),
    'reason', purchase_lock_reason,
    'updated_at', updated_at
  )
  from public.m4x_store_control
  where id='main';
$$;

revoke all on function public.m4x_store_purchase_status() from public;
grant execute on function public.m4x_store_purchase_status() to anon,authenticated;

-- 2) Telegram admin conversational state.
create table if not exists public.telegram_admin_sessions (
  telegram_user_id text primary key,
  state text not null default '',
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.telegram_admin_sessions enable row level security;
revoke all on public.telegram_admin_sessions from public,anon,authenticated;

-- 3) AI caption history (server-only).
create table if not exists public.telegram_ai_caption_history (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references auth.users(id) on delete set null,
  product_id uuid references public.products(id) on delete set null,
  tone text not null default 'sale',
  caption_length text not null default 'medium',
  extra_instruction text,
  caption text not null,
  provider text not null default 'openai',
  model text,
  created_at timestamptz not null default now()
);

create index if not exists idx_tg_ai_caption_history_created
on public.telegram_ai_caption_history(created_at desc);

alter table public.telegram_ai_caption_history enable row level security;
revoke all on public.telegram_ai_caption_history from public,anon,authenticated;

notify pgrst,'reload schema';
commit;

select 'M4X V19.4 AI Caption + Telegram Button Admin installed successfully' as result;
